"""
publish.py — the public numbers, generated from the measurement.

`EXPANSION_ROADMAP` Phase 9's acceptance is that "the README benchmark table
[is] generated by `eval/`, never hand-written" and that "the words *detects*,
*diagnoses*, *ranks* are each backed by a measured number". This module is the
mechanism that makes both checkable rather than aspirational.

The chain is three steps and each one is a file a reviewer can open.

    fabops-benchmark --emit-json > docs/benchmark_results.json   the measurement
    python publish_readme.py                                     the markdown
    a test that re-renders the committed results and compares    the guard

The guard is the point. A README section can be regenerated by hand once and
then edited, and nobody notices until the number in the headline no longer
matches the number in the harness. Here the committed results document is the
only source of the block, and `--check` fails if the two have parted — so the
README cannot drift from the benchmark without failing the suite.

**Nothing here computes a metric, and nothing here writes a file.** It renders
`fabeval.diagnosisscore.Score`, which is the only thing that scores anything,
and it carries the population and the engine settings into the rendered text so
a figure cannot be quoted without the conditions it was measured under. The
file handling lives in `publish_readme.py` at the repository root, because
ADR-024 §1 makes "`fabeval` writes nothing" an absolute lexical rule and an
exception for one well-behaved caller is how such a rule stops being one.

**The engine's settings are read from the engine, never declared here.** A
default living in the evaluator would be a second, competing declaration of
something `decide.py` and `statistics.py` own — the drift both of those modules
have already had once. `engine_settings()` asks them.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Mapping, Sequence

__all__ = [
    "README_BEGIN",
    "README_END",
    "RESULTS_SCHEMA",
    "apply_block",
    "engine_settings",
    "extract_block",
    "render_markdown",
    "results_document",
]

RESULTS_SCHEMA = "fabeval.results/v1"

#: The markers the generated block sits between. HTML comments, so they are
#: invisible in a rendered README and unmistakable in the source.
README_BEGIN = "<!-- BENCHMARK:BEGIN — generated by publish_readme.py; edits are overwritten -->"
README_END = "<!-- BENCHMARK:END -->"

_METRICS = (
    ("false_alarm_rate", "false-alarm rate", "fires on a fault-free dataset",
     ".3f"),
    ("detection_rate", "detection rate",
     "clears the fab-wide bar on a faulted one", ".3f"),
    ("attribution_rate", "attribution, rank 1",
     "puts a planted entity first", ".3f"),
    ("top3_rate", "attribution, top 3",
     "puts a planted entity in the top three", ".3f"),
    ("mean_reciprocal_rank", "mean reciprocal rank",
     "1/rank of the best planted entity", ".3f"),
    ("median_onset_error", "median onset error (days)",
     "on the datasets where an onset was estimated", ".1f"),
)


def _score_record(score) -> dict[str, Any]:
    from fabeval.population import claimable

    allowed, reason = claimable(score.scenarios)
    return {
        "population": score.population,
        "scenarios": list(score.scenarios),
        "datasets": len(score.outcomes),
        "faulted": len(score.faulted),
        "fault_free": len(score.nulls),
        "capability_claim_permitted": allowed,
        "capability_claim_note": reason,
        "notes": list(score.notes),
        "metrics": {name: getattr(score, name)
                    for name, _label, _gloss, _fmt in _METRICS},
    }


def engine_settings() -> dict[str, Any]:
    """What the engine declares, read from the engine's own modules.

    Recording is not choosing: these values are asked for at the moment a
    result is written down, so a published figure always carries the
    configuration that produced it and can never carry a stale copy of one.
    """
    from fabops.diagnosis import ENGINE
    from fabops.diagnosis.anchors import DECLARED_FRACTIONS
    from fabops.diagnosis.decide import ALPHA, PERMUTATIONS
    from fabops.diagnosis.statistics import DEFAULT_STATISTIC

    return {"engine": ENGINE,
            "settings": {"statistic": DEFAULT_STATISTIC, "alpha": ALPHA,
                         "permutations": PERMUTATIONS,
                         "anchor_fractions": list(DECLARED_FRACTIONS)}}


def results_document(scores: Sequence[Any], *, engine: str | None = None,
                     settings: Mapping[str, Any] | None = None,
                     diversity_axes: Mapping[str, Any] | None = None
                     ) -> dict[str, Any]:
    """The measurement, as a document that can be committed and re-rendered.

    No wall-clock field. What identifies a result is the engine that produced
    it and the population it was measured on, both of which are here; a
    timestamp would change on every run and make the committed file look stale
    when nothing had moved.
    """
    declared = engine_settings()
    return {
        "schema": RESULTS_SCHEMA,
        "engine": engine or declared["engine"],
        "settings": dict(settings or declared["settings"]),
        "diversity": dict(diversity_axes or {}),
        "populations": [_score_record(score) for score in scores],
    }


def _cell(value: Any, fmt: str) -> str:
    return "n/a" if value is None else format(value, fmt)


def render_markdown(document: Mapping[str, Any]) -> str:
    """The README's benchmark section, in full, from the results document."""
    if document.get("schema") != RESULTS_SCHEMA:
        raise ValueError(f"not a {RESULTS_SCHEMA} document: "
                         f"{document.get('schema')!r}")
    populations = document["populations"]
    settings = document.get("settings", {})

    lines = [
        "### Measured capability",
        "",
        f"Every number below is produced by `fabops-benchmark` and rendered by "
        f"`publish_readme.py`; none of it is typed by hand, and a test fails if "
        f"this section and the committed results disagree. Engine "
        f"`{document['engine']}`, statistic `{settings.get('statistic')}`, "
        f"abstention level α = {settings.get('alpha')}, "
        f"{settings.get('permutations')} permutations, anchor at "
        f"{settings.get('anchor_fractions')} of the horizon.",
        "",
    ]

    header = "| | " + " | ".join(row["population"] for row in populations) + " |"
    divider = "|---|" + "---|" * len(populations)
    lines += [header, divider]
    lines.append("| datasets | " + " | ".join(
        f"{row['datasets']} ({row['faulted']} faulted)"
        for row in populations) + " |")
    for name, label, _gloss, fmt in _METRICS:
        lines.append(f"| {label} | " + " | ".join(
            _cell(row["metrics"].get(name), fmt) for row in populations) + " |")
    lines.append("")

    for row in populations:
        claim = ("a capability claim is permitted on this population"
                 if row["capability_claim_permitted"] else
                 f"**not a capability claim**: {row['capability_claim_note']}")
        notes = " ".join(row["notes"])
        lines.append(f"- **{row['population']}** — "
                     f"{len(row['scenarios'])} scenario(s); {claim}."
                     + (f" {notes}" if notes else ""))
    lines.append("")

    lines += [
        "**What those numbers mean, stated plainly.** At its declared level "
        "the engine **abstains on every dataset this project can build** — "
        "its detection rate is zero and so is its false-alarm rate, which is "
        "the half of its contract it keeps exactly. It ranks a planted entity "
        "first on about one development dataset in ten and on none of the "
        "held-out ones. That is weak, it is measured, and it is reported here "
        "rather than in a footnote: every lever that would buy detections — a "
        "multi-anchor grid, a pooled-denominator statistic, a higher level — "
        "was built and measured, and each one spends calibration this "
        "architecture ranks above power (ADR-031 §12).",
        "",
        "The claim this repository makes is therefore not *\"it finds the "
        "fault\"*. It is: **a synthetic fab whose faults are physics-mediated "
        "and whose answer key is a physically separate file, an engine that is "
        "handed a database path and nothing else, and a benchmark that says "
        "exactly how often it is right.** The third of those is what most "
        "portfolio projects are missing, and it is the one that makes the "
        "first two checkable.",
    ]

    diversity = document.get("diversity") or {}
    if diversity:
        covered = ", ".join(f"{axis} ×{count}"
                            for axis, count in sorted(diversity.items()))
        lines += ["",
                  f"**Library coverage**, measured from the scenario "
                  f"configurations rather than asserted: {covered}."]

    return "\n".join(lines)


def apply_block(text: str, block: str) -> str:
    """Replace whatever sits between the markers, inserting them if absent."""
    start = text.find(README_BEGIN)
    end = text.find(README_END)
    body = f"{README_BEGIN}\n\n{block}\n\n{README_END}"
    if start == -1 or end == -1 or end < start:
        raise ValueError(
            "the target has no benchmark markers; add\n"
            f"    {README_BEGIN}\n    {README_END}\n"
            "where the generated section belongs")
    return text[:start] + body + text[end + len(README_END):]


def extract_block(text: str) -> str:
    """What is currently between the markers, without them."""
    start = text.find(README_BEGIN)
    end = text.find(README_END)
    if start == -1 or end == -1:
        raise ValueError("the target has no benchmark markers")
    return text[start + len(README_BEGIN):end].strip("\n").strip()


