"""
The public numbers are generated, and cannot drift from the measurement.

`EXPANSION_ROADMAP` Phase 9's acceptance is that the README's benchmark table
is "generated by `eval/`, never hand-written". A generator alone does not
achieve that — a section can be generated once and then edited, and the edit is
invisible until somebody re-runs the harness a year later. What achieves it is
the guard below: the committed results document is re-rendered and compared
against what the README actually contains, so the two cannot part company
without failing the suite.

Nothing here builds a dataset. The measurement itself lives in
`fabops-benchmark`, is expensive, and is recorded in
`docs/benchmark_results.json`; these tests are about the path from that file to
the public surface.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from fabeval.publish import (README_BEGIN, README_END, RESULTS_SCHEMA,
                             apply_block, extract_block, main, render_markdown,
                             results_document)

REPO = Path(__file__).resolve().parents[2]
RESULTS = REPO / "docs" / "benchmark_results.json"
README = REPO / "README.md"


@pytest.fixture(scope="module")
def document():
    if not RESULTS.exists():                             # pragma: no cover
        pytest.skip("the benchmark results have not been emitted")
    return json.loads(RESULTS.read_text(encoding="utf-8"))


def test_the_results_document_is_what_it_says_it_is(document):
    assert document["schema"] == RESULTS_SCHEMA
    assert document["engine"].startswith("fabops.diagnosis/")
    settings = document["settings"]
    assert set(settings) == {"statistic", "alpha", "permutations",
                             "anchor_fractions"}
    assert document["populations"], "no population was scored"


def test_the_settings_are_the_ones_the_engine_actually_ships(document):
    """A results file that recorded a different level from the one the engine
    defaults to would publish a number nobody can reproduce."""
    from fabops.diagnosis import ENGINE
    from fabops.diagnosis.anchors import DECLARED_FRACTIONS
    from fabops.diagnosis.decide import ALPHA, PERMUTATIONS
    from fabops.diagnosis.statistics import DEFAULT_STATISTIC

    assert document["engine"] == ENGINE
    settings = document["settings"]
    assert settings["statistic"] == DEFAULT_STATISTIC
    assert settings["alpha"] == ALPHA
    assert settings["permutations"] == PERMUTATIONS
    assert list(settings["anchor_fractions"]) == list(DECLARED_FRACTIONS)


def test_every_population_carries_its_own_claim_verdict(document):
    """`fabeval.population.claimable` is the guard that stops a development
    figure being quoted as a capability. It has to reach the public surface."""
    for population in document["populations"]:
        assert "capability_claim_permitted" in population
        assert population["datasets"] == (population["faulted"]
                                          + population["fault_free"])
        assert population["scenarios"]


def test_the_library_row_is_the_one_a_claim_is_permitted_on(document):
    """Neither half of the split reaches ten scenarios, so a claim is permitted
    only on the pooled library — and the pooled row must be there or the
    project cannot state in one sentence what its engine does."""
    permitted = [row for row in document["populations"]
                 if row["capability_claim_permitted"]]
    assert permitted, ("no population permits a capability claim; the pooled "
                       "library row is missing from the results document")
    assert any(len(row["scenarios"]) >= 10 for row in permitted)


def test_the_rendered_block_states_the_conditions_and_the_verdict(document):
    block = render_markdown(document)
    assert "fabops-benchmark" in block and "fabops-publish" in block
    assert str(document["settings"]["alpha"]) in block
    assert document["engine"] in block
    for population in document["populations"]:
        assert population["population"] in block
    # The result that must never be quietly dropped.
    assert "abstains on every dataset" in block


def test_a_document_of_the_wrong_schema_is_refused():
    with pytest.raises(ValueError, match="fabeval.results/v1"):
        render_markdown({"schema": "somebody.else/v3", "populations": []})


def test_apply_and_extract_round_trip():
    text = f"before\n\n{README_BEGIN}\n\nold\n\n{README_END}\n\nafter\n"
    updated = apply_block(text, "new content")
    assert extract_block(updated) == "new content"
    assert updated.startswith("before")
    assert updated.endswith("after\n")


def test_a_target_without_markers_is_refused():
    with pytest.raises(ValueError, match="markers"):
        apply_block("no markers here", "x")


def test_the_readme_matches_the_committed_measurement(document):
    """The guard. If this fails, either the README was edited by hand or the
    benchmark was re-run without republishing — and in both cases a number on
    the project's front page no longer matches the harness that produced it.

    Fix by running:
        fabops-publish --results docs/benchmark_results.json --readme README.md
    """
    text = README.read_text(encoding="utf-8")
    assert README_BEGIN in text and README_END in text, (
        "the README lost its benchmark markers")
    assert extract_block(text) == render_markdown(document)


def test_the_check_mode_agrees(document, capsys):
    assert main(["--results", str(RESULTS), "--readme", str(README),
                 "--check"]) == 0
    assert "matches" in capsys.readouterr().out


def test_the_check_mode_fails_on_a_stale_target(tmp_path, document):
    """The mirror: a guard that cannot fail is not a guard."""
    stale = tmp_path / "README.md"
    stale.write_text(f"{README_BEGIN}\n\nstale numbers\n\n{README_END}\n",
                     encoding="utf-8")
    assert main(["--results", str(RESULTS), "--readme", str(stale),
                 "--check"]) == 1


def test_results_document_needs_no_wall_clock(document):
    """What identifies a result is the engine and the population, both of which
    are recorded. A timestamp would change on every run and make a committed
    file look stale when nothing had moved."""
    serialized = json.dumps(document)
    for word in ("generated_at", "timestamp", "created_at"):
        assert word not in serialized
